# Site settings
title: Open source blog
#email: jan.vejsada@seznam.cz
description: > # this means to ignore newlines until "baseurl:"
  Web builder using the Jekyll :-) .

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vejsada.github.io/blog/" # the base hostname & protocol for your site

twitter_username: JanVejsada
github_username:  vejsada

# Build settings
markdown: kramdown

